import java.net.URI

/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/7.3.2/userguide/multi_project_builds.html
 */

rootProject.name = "siardcmd"


sourceControl {
    gitRepository(URI.create("https://github.com/sfa-siard/EnterUtilities")) {
        producesModule("ch.admin.bar:enterutilities")
    }

    gitRepository(URI.create("https://github.com/sfa-siard/JdbcPostgres")) {
        producesModule("ch.admin.bar:JdbcPostgres")
    }

    gitRepository(URI.create("https://github.com/sfa-siard/JdbcOracle")) {
        producesModule("ch.admin.bar:jdbcoracle")
    }

    gitRepository(URI.create("https://github.com/sfa-siard/JdbcMsSql")) {
        producesModule("ch.admin.bar:jdbcmssql")
    }

    gitRepository(URI.create("https://github.com/sfa-siard/SiardApi")) {
        producesModule("ch.admin.bar:siard-api")
    }
}