ALTER SESSION SET CONTAINER=XEPDB1;

CREATE TABLE IT_USER.SAMPLE_TABLE (
    ID NUMBER PRIMARY KEY,
    AGE NUMBER,
    HEIGHT_IN_CM NUMBER(3),
    HEIGHT_IN_M NUMBER(3,2)
);

INSERT INTO IT_USER.SAMPLE_TABLE (ID, AGE, HEIGHT_IN_CM, HEIGHT_IN_M)
VALUES (1, 25, 175, 1.75);

INSERT INTO IT_USER.SAMPLE_TABLE (ID, AGE, HEIGHT_IN_CM, HEIGHT_IN_M)
VALUES (2, 30, 180, 1.80);

INSERT INTO IT_USER.SAMPLE_TABLE (ID, AGE, HEIGHT_IN_CM, HEIGHT_IN_M)
VALUES (3, 35, 170, 1.70);

