ALTER SESSION SET CONTAINER=XEPDB1;

CREATE USER IT_USER IDENTIFIED BY password QUOTA UNLIMITED ON USERS;

GRANT CONNECT, RESOURCE TO IT_USER;

GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE TRIGGER, CREATE PROCEDURE TO IT_USER;

GRANT DBA TO IT_USER;

CREATE USER MY_TEST IDENTIFIED BY password QUOTA UNLIMITED ON USERS;

GRANT CONNECT, RESOURCE TO MY_TEST;
