ALTER SESSION SET CONTAINER=XEPDB1;

CREATE USER MY_TEST IDENTIFIED BY password QUOTA UNLIMITED ON USERS;

GRANT CONNECT, RESOURCE TO MY_TEST;

GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE TRIGGER, CREATE PROCEDURE TO MY_TEST;

GRANT DBA TO MY_TEST;