ALTER SESSION SET CONTAINER=XEPDB1;

CREATE TABLE TEST.SAMPLE_TABLE
(
    ID    NUMBER,
    DESCRIPTION VARCHAR2(128)
);
INSERT INTO TEST.SAMPLE_TABLE(ID, DESCRIPTION)
VALUES (1, 'Test Oracle Download with SIARD CMD');


CREATE FUNCTION TEST.TEST_FN(p_bool BOOLEAN) RETURN VARCHAR2 IS
BEGIN
    IF p_bool THEN
        RETURN 'TRUE';
    ELSE
        RETURN 'FALSE';
    END IF;
END;
/



