ALTER SESSION SET CONTAINER=XEPDB1;
CREATE USER SIARDTEST IDENTIFIED by SIARDTEST QUOTA UNLIMITED ON USERS;
GRANT RESOURCE TO SIARDTEST;
GRANT CONNECT TO SIARDTEST;
GRANT CREATE SESSION TO SIARDTEST;
ALTER USER SIARDTEST DEFAULT ROLE ALL;

create table mytable
(
    id    number,
    descr varchar2(128)
);
insert into mytable(id, descr)
values (1, 'HELLO WORLD');

CREATE
OR REPLACE FUNCTION bool_to_string(p_bool BOOLEAN) RETURN VARCHAR2 IS
BEGIN
IF
p_bool THEN
RETURN 'TRUE';
ELSE
RETURN 'FALSE';
END IF;
END;