# This workflow will build a Java project with Ant
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-ant

name: Test and build with ant

on:
  push:
    branches:
      - master
      - dev/pitc-*
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: run docker-compose
        run: docker-compose up -d
        # TODO: find a better way to wait until the database is ready
      - name: Sleep for 100 seconds
        run: sleep 100s
        shell: bash
      - name: check logs of docker-compose
        run: docker-compose logs
      - name: MS Access DB Tests
        run: ant -noinput -buildfile build.xml test-access
      - name: PostgresQL DB Tests
        run: ant -noinput -buildfile build.xml test-postgres
