# This workflow will build a Java project with Ant
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-ant

name: Build project

on:
  push:
    branches:
      - main
      - feature/*
      - issue/*
  pull_request:
    branches: [ main ]

jobs:
  test-issues:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Run Tests for specific issues
        run: ./gradlew test --tests ch.admin.bar.siard2.cmd.issues.*
      - name: Run integration tests
        run: ./gradlew integrationTest



