# This workflow will build a Java project with Ant
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-ant

name: Continuous build windows-latest

on:
  push:
    branches:
      - feature/*
      - issue/*
      - chore/*
jobs:
  execute-unit-tests:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'


      - name: Java version
        run: java -version

      - name: Build with Gradle (Windows debug)
        shell: bash
        run: |
          ./gradlew build --info --console=plain --stacktrace 2>&1 | tee gradle.log

      - name: Upload Gradle log
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: gradle-log
          path: gradle.log

      - name: Store reports
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: |
            **/build/reports/
            **/build/test-results/
