name: Integration build

on:
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  execute-unit-and-integration-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macOS-latest, windows-latest ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Run unit tests
        run: ./gradlew test
      - name: Run integration tests
        run: ./gradlew integrationTest
      - name: Store reports
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: |
            **/build/reports/
            **/build/test-results/
