# This workflow will build a Java project with Ant
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-ant

name: Build project

on:
  push:
    branches:
      - main
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "0 0 * * *" # end of the day

jobs:
  execute-unitand-integration-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Run unit tests
        run: ./gradlew test
      - name: Run integration tests
        run: ./gradlew integrationTest
